Update how to deploy
rethinkdb/rethinkdb-java pull request #45
Opened 2020-03-28 11:09 UTC by gabor-boros

Unfortunately, there is a race condition when signing pom and uploading artifacts. Update the execution order of gradle tasks.

2020-04-22 00:19 UTC, NotJustAnna requested changes

2020-04-22 00:19 UTC, adriantodt commented on DEPLOYING.md
> +To upload a new release, run `./gradlew assemble signArchives` **after that** run `./gradlew bintrayUpload`. Unfortunately, there is a race condition when signing pom and uploading artifacts. This sh
This shouldn't be needed because `mustRunAfter` fixes the race condition and can be reverted.

2020-04-22 16:16 UTC, gabor-boros commented
@adriantodt Thanks! I’ll update this PR tomorrow

2020-04-23 14:52 UTC, NotJustAnna approved these changes

2020-04-23 15:32 UTC, merged